# Generated by Django 5.1.1 on 2024-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='phoneme_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
