# Generated by Django 5.1.1 on 2024-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedprogress',
            name='correct_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detailedprogress',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
    ]
