# Generated by Django 5.1.1 on 2024-09-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_detailedprogress_correct_words_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='total_level',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='correct_words',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_words',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='accuracy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DetailedProgress',
        ),
    ]
