# Generated by Django 5.1.1 on 2024-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_remove_userprogress_total_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='level',
            field=models.IntegerField(default=None),
        ),
    ]
