# Generated by Django 5.1.1 on 2024-09-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_userprogress_missed_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='missed_words',
        ),
    ]
