# Generated by Django 5.1.1 on 2024-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_userprogress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
