# Generated by Django 5.1.1 on 2024-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_alter_userprogress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='accuracy',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='correct_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
    ]
